# Setup
title:               Dimensions interest me.
tagline:             Hemant's Blog
description:         I look upto SHIVA whenever I'm confused.
url:                 https://raotnameh.github.io
baseurl:             '/about'
paginate:            10
permalink:           pretty

# About/contact
author:
  name:       Hemant Yadav       
  url:        https://raotnameh.github.io
  email:      hemantya@iiitd.ac.in

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
