# Setup
title:               Dimensions (1D, 2D, 3D, ..., nD) interest me.
tagline:             Hemant\'s Blog
#description:        'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:         'I like to look upto SHIVA whenever I\'m confused.'
url:                 https://raotnameh.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:       Hemant Yadav       
  url:        https://raotnameh.github.io/
  email:      hemantya@iiitd.ac.in

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
