# Setup
title:               If you can not code it right, you do not understand it. 
tagline:             Hemant's Blog
description:         I look upto SHIVA whenever I'm confused.
url:                 https://raotnameh.github.io
baseurl:             ''
paginate:            6
permalink:           pretty

# About/contact
author:
  name:       Hemant Yadav       
  url:        https://raotnameh.github.io
  email:      hemantya@iiitd.ac.in

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
